### ISSUE TITLE
Known Contacts list is sorted with capitalized letters first. 

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1036]
Go to Contacts screen

Xray

will come before

delta

**Comment by undercase** [comment]
It seems like this was fixed in #1038, which converts names to lowercase using `toLowerCase()` before comparing them. When I tried to reproduce the error, contacts were sorted correctly regardless of case. Am I looking at the wrong screen?

**Comment by andrewxhill** [comment]
boom! must have slipped my mind, good to close here
