### ISSUE TITLE
Can't select profile photo during onboarding

### ISSUE THREAD

**Issue by arfonzocoward** [textileio/photos#1041]
**Describe the bug**
Can't select a photo in the Android app. Nothing happens when trying to select a picture from device. The onboarding doesn't progress, nor any additional output to understand what's happened.

**To Reproduce**
1. Onboard.
2. Select photo.
3. Try to progress.

**Expected behavior**
Error, and progression onto complete onboarding.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6, unrooted.
 - OS: Android 9
 - Version 0.5.20

**Additional context**
Reported via twitter, requested to submit this ticket.

**Comment by andrewxhill** [comment]
Having a hard time replicating. 

Success on a Pixel 3 with latest and on a Nexus One with 9.0. 

- Could you share a screenshot of the app state after adding the avatar?
- Could you try a vanilla jpeg, maybe grab one from unsplash.com to try, just to eliminate any issues maybe caused by the file.

**Comment by arfonzocoward** [comment]
Sure, so I have played around a bit more:

- No matter what image format/size/source I try to pick from, nothing happens. See attached. Have tried from Gallery and Google Photos.
- It occurs with generic downloaded jpgs as well as pictures saved from my camera.
- Interestingly, if I take a picture with my Camera instead of picking a file, this seems to work.

I have attached the screenshots for you.

Choose photo:

![image](https://user-images.githubusercontent.com/19427797/56227021-71978280-606c-11e9-850d-4ff147b73474.png)

After choosing:
![image](https://user-images.githubusercontent.com/19427797/56227066-896f0680-606c-11e9-8880-eb5a77d2b1d7.png)

Taking picture from camera works:
![image](https://user-images.githubusercontent.com/19427797/56227104-9c81d680-606c-11e9-9d5d-df4af3630a0f.png)


Thanks!

**Comment by andrewxhill** [comment]
very strange. your permissions for the app match?

![Screen Shot 2019-04-16 at 9 51 06 AM](https://user-images.githubusercontent.com/370259/56228735-39bd1a80-602d-11e9-9374-8f619015ed93.png)

**Comment by arfonzocoward** [comment]
Yes, exactly as you've shown.

**Comment by andrewxhill** [comment]
Still can't pin it. Definitely just continue with your onboarding, sorry about this. It'll be interesting, once you are onboarded, try and change your avatar using camera roll and let us know if it works then.

**Comment by arfonzocoward** [comment]
No problem.

I have now completed onboarding by taking a picture with the camera. Once in the app, I'm still not able to select pictures, with the same behaviour as in the original ticket.

**Comment by andrewxhill** [comment]
Okay, a bit of a shot in the dark but tried to revert some changes that may be responsible. @arfonzocoward when you have some time, could you update and try adding a photo again?

**Comment by arfonzocoward** [comment]
Thanks, however no luck I'm afraid. I've updated the app this morning to try, with the same results. I'm wondering whether anyone else with any OnePlus could try to replicate?

**Comment by estensen** [comment]
Same issue with a Pixel 2XL and Android Q

**Comment by arfonzocoward** [comment]
Having played with the app further, this isn't an issue just isolated to the onboarding. Any picture selection call, both during and after onboarding, have this behaviour.

Hopefully now that someone else can confirm this behaviour it can be easier to isolate and reproduce.

Thanks.

**Comment by ca057** [comment]
I have the same issue with a Huawei P20 Pro and Android 9.

**Comment by andrewxhill** [comment]
another clue from a user,

`If it helps, I worked it out. I had multiple intent listeners that could handle that intent. When I locked in one as "always" handling it, I was able to set a photo and move on.`

**Comment by andrewxhill** [comment]
Sorry that took so long. I think I've just fixed it. I'll try to get a release out first thing in the morning.
