### ISSUE TITLE
Remove a contact

### ISSUE THREAD

**Issue by sanderpick** [textileio/photos#1051]
Per user request, you should be able to delete a contact from your "address book". The API support this: `removeContact`

**Comment by undercase** [comment]
I went through the code and added some basic contact removal functionality. Here are my thoughts on this:

I imagine that there are two places users may want to remove a contact:

1. The `Contacts` screen, which should have a remove button attached to each item.
2. The `Contact` screen, which should have a button that lets users add a contact (if they haven't already, and navigated to the screen from the `AddContact` screen) or remove a contact (if they have already added it, and navigated to the screen from the `Contacts` screen).

(Note: Although at first it seems like they should also be able to remove contacts from the `AddContact` screen, if their search results contain a contact they've already added, I think it's bad practice to show contacts they've already added at all on the search screen.)

Ideally, both of the above screens will share the same functionality. Right now, you cannot add a contact from the `Contact` screen after you click through to it from the `AddContact` search screen. Thus, the ability to add a contact from the `Contact` screen must be added along with the ability to remove one. I'll start by adding this functionality on the `Contacts` screen, and then move on to adding both addition and removal to the `Contact` screen.
