### ISSUE TITLE
Tripple file upload notification for Android

### ISSUE THREAD

**Issue by estensen** [textileio/photos#1054]
**Describe the bug**
When uploading a photo I get three identical upload notifications

**To Reproduce**
1. Open Textile Photos
2. Create a group
3. Upload picture to the group

**Expected behavior**
A single notification

**Smartphone (please complete the following information):**
 - Device: Pixel 2XL
 - OS: Android
 - Version Q (beta)

**Additional context**
I actually don't want any notifications that my files were successfully uploaded. How can I turn this off?

**Comment by asutula** [comment]
Hey thanks for opening an issue. When you share a photo in Textile Photos, there are actually three uploads that happen: small, medium, and high resolution files. We're using a library for uploading the files that, by default, displays a notification for each upload. We're currently in the process of writing our own custom uploading code that will handle notifications is a better way. You can track progress here https://github.com/textileio/android-textile/issues/17
