### ISSUE TITLE
Add button to contact card to create a new p2p group (should use whitelist)

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1060]

**Comment by undercase** [comment]
Do you essentially want a button to open a direct message chat with another contact?

**Comment by andrewxhill** [comment]
yes. but... @asutula @sanderpick and I have spoken about this in the past a few times. i'm not certain the current best idea to achieve it. 

As in. 

Setup: Contacts A and B

Goal: A wants to send a message to B. 

1. Should A look through existing threads to see if there is already a thread with MEDIA schema that only contains A & B in the whitelist? If so, just re-use that one?
2. If not, A should probably create that thread and send a P2P invite to user B. Should the invite be a little different in appearance or messaging for B since this is a special thread (member whitelisted)?
3. Do we want to have a plan to deal with edge case, A tries to create and send an invite. Be tries to create and send an invite before seeing or receiving the one from A. 
4. Do we want to add a helper to the clients to search for the 2 member thread types more easily? getP2P threads or `getThreadsWith(contact.address, p2p?: boolean)` or something like that

**Comment by undercase** [comment]
I need to re-read the documentation on threads and look through the sdk to figure out exactly how I'm going to do this. For the time being, here's my take:

1. If there's already a thread, I think the app should just re-use that one. I'm imagining this as a button like "Create Thread" / "Open Thread" / "Send Message" on the Contact modal, and I think it'd be confusing for users if they ended up having several threads with the same person.

2. I think it makes sense to make the invite different from a ux perspective.

3. I'm not sure how to handle this-I'm not familiar enough with what's going on behind the scenes. Deferring.

4. Ditto.

**Comment by undercase** [comment]
Tackling this right now. The plan for the time being is to create a button that says "Direct Message" on the contact modal. When this is clicked, it will search for an existing thread and go to that one if it is found. If it can't find one, it will create a new one and navigate to it. For now, I'm going to leave the invite the same, and pull that feature into a separate issue.

In the future, having some code to handle edge cases / a client helper would be great. I'm going to write this feature with the client features available now, but make sure it's future proof so it'll be easy to switch over to using helpers like `getThreadsWith` later.

**Comment by undercase** [comment]
Fixed in #1094.
