### ISSUE TITLE
Error loading react-native-camera-roll in Android Studio

### ISSUE THREAD

**Issue by undercase** [textileio/photos#1069]
**Describe the bug**
Android studio can't load `react-native-camera-roll`. The application still runs, but throws this error on sync.

**To Reproduce**
1. Clone the repository
2. Run `npm i`
3. Open the project in android studio
4. See error:

```
Cannot load module file 'C:/Users/hoboh/Documents/Textile/photos/node_modules/@textile/react-native-camera-roll/android/@textile_react-native-camera-roll.iml':
File C:\Users\hoboh\Documents\Textile\photos\node_modules\@textile\react-native-camera-roll\android\@textile_react-native-camera-roll.iml does not exist
Would you like to remove module '@textile_react-native-camera-roll' from the project?
```

**Expected behavior**
The application should sync successfully.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Latest

**Smartphone (please complete the following information):**
- Genymotion android emulator - Google Nexus 5X

**Comment by andrewxhill** [comment]
what's the status here?

**Comment by undercase** [comment]
This is resolved.
