### ISSUE TITLE
Line heights messed up with emojis

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1071]
![photo_2019-05-18 14 24 47](https://user-images.githubusercontent.com/370259/57975152-d0f0f700-7978-11e9-9ffe-3c4d0c95bdfc.jpeg)

**Comment by undercase** [comment]
It seems like we can fix this by making the line height [the `fontSize` + 8, according to this issue](https://github.com/FaridSafi/react-native-gifted-chat/issues/229#issuecomment-248808102). I'll experiment a bit and see what works best.
