### ISSUE TITLE
Make links shared in chats clickable

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1072]
Simple as that, currently they are rendered as plain text.

**Comment by undercase** [comment]
Making links render w/ special styling and clickability right now. Long-term, it might be nice to have some sort of link preview, a la iMessage.

**Comment by undercase** [comment]
Thoughts on adding [Linkify](https://soapbox.github.io/linkifyjs/) as a dependency to handle this behavior?

**Comment by asutula** [comment]
Gonna be the grumpy, slow, old guy and say we should seriously consider or at least come up with a plan about how to not just hack these types of things in. Is there some way we can support rich text in a structured way? If so, we'll then have a system for supporting more than just links.

**Comment by undercase** [comment]
You're right, we should think of a more robust way to support text formatting. It's certainly a cliche at this point, but what about adding Markdown support, since everyone and their dog is familiar with it?

**Comment by asutula** [comment]
Linkify looks like a great tool, especially for automatically detecting things that should be links, even if the user didn't format them as links in a rich text editor.

**Comment by asutula** [comment]
Markdown would be one choice for a supported format. HTML is the other obvious one. Will have to research more.

**Comment by undercase** [comment]
For sure. Whatever format we choose, we'll probably need a tool like Linkify to detect things that should be links but aren't formatted as such. How about I implement link detection with Linkify and open a separate issue to add support for rich text?

**Comment by asutula** [comment]
Sounds like a good plan
