### ISSUE TITLE
Release to production

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1076]
Just following up on a Thread over the weekend. It's been quite a while since we did a release, so it would be handy.

- [ ] Ensure auto-import isn't happening when not flagged.  https://github.com/textileio/photos/issues/1067
- [ ] Get latest mobile enhancements into app. https://github.com/textileio/go-textile/releases/tag/v0.1.14

**Comment by asutula** [comment]
Done.

**Comment by andrewxhill** [comment]
Are either of these blocking release?

https://github.com/textileio/photos/issues/1085

https://github.com/textileio/photos/issues/1083

**Comment by asutula** [comment]
Not sure. I haven't seem those problems. Anyone else?

Did those happen when installing the latest beta?

**Comment by andrewxhill** [comment]
The wiped state I'm not certain. I believe it was after doing an update yesterday.

The blank screen i can get anytime launching out of a hard kill.
