### ISSUE TITLE
Add some prompt on contacts screen when user has no contacts

### ISSUE THREAD

**Issue by undercase** [textileio/photos#1090]
Right now, if you have no contacts and navigate to the contacts screen, it is simply blank, and the search bar is active. If a user has no contacts the search bar should be disabled and there should be a prompt telling them to add a contact, like the `Create New Group` button on the groups screen.

**Comment by andrewxhill** [comment]
i was wondering why search should be different for local or unknown users? 

right now, if you search, it breaks them into groups (icloud, decentralized), why not just put your existing contacts as a 3rd group in that search? and then the primary search bar is all you need, no "+"

**Comment by undercase** [comment]
That makes sense. I think it'd be ideal to put the existing contacts (if any match the search) at the top from a ux perspective, then icloud and decentralized contacts. Would eliminate the AddContact screen entirely and refactor it into the Contacts screen.

**Comment by undercase** [comment]
This could be done at the same time as extending contacts search with some basic fuzzy search functionality.
