### ISSUE TITLE
Rename Groups not completing successfully

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1093]
Seeing some issues with this in the current Beta release.

https://github.com/textileio/photos/pull/1084

1. I went to change the name the first time. Edited the name and clicked 'Rename'. Nothing happened, it just stayed on the rename interface. 
2. Clicked 'Cancel', as that was the only option left, and it wasn't renamed
3. Hard-killed and went back to group. Went to rename interface. Now, if I edit the name, the 'Rename' option never become clickable so I can only 'Cancel'. Group is still the original name from before step 1.

**Comment by undercase** [comment]
I'll fix this today-pretty sure I made a small mistake when I was refactoring a function name for the linter.

**Comment by asutula** [comment]
I've seen this as well. It does work sometimes, though. @undercase are you displaying an error on that rename modal if an error happens?

**Comment by undercase** [comment]
I knew I was forgetting something-right now it doesn't do anything w/ the error message if there is one, but the error in the redux state blocks you from renaming it again. Will fix it today after I finish the direct message PR.

**Comment by asutula** [comment]
Yea makes sense. Will be interesting to see what this error is that sometimes happens when renaming.

**Comment by andrewxhill** [comment]
![IMG_0CEB5BA9633F-1](https://user-images.githubusercontent.com/370259/59051484-d5a31f80-8841-11e9-8b55-d8cc9fe8f311.jpeg)

**Comment by sanderpick** [comment]
I believe you'll get that error if you're not the thread initiator

**Comment by undercase** [comment]
I assumed anyone could rename the thread. I'll fix this by not showing the rename group button if the user isn't the initiator.

**Comment by andrewxhill** [comment]
same, i was under the impression that this was a local change only, not something that would be distributed to other thread members

**Comment by undercase** [comment]
I figured it was like messenger groups, in that anyone can rename it and it is distributed to everyone else in the group. Looks like it is distributed to everyone else in the group, but only the initiator can change it.

**Comment by asutula** [comment]
I mean, the behavior we thought should be there is what should be there. Maybe we should just have go-textile apply some logical permissions to editing the thread name based on the thread permissions?

**Comment by sanderpick** [comment]
No problem, @undercase - I would have mentioned had I been paying attention. The current behavior is documented in the go doc: https://github.com/textileio/go-textile/blob/master/core/threads.go#L257

**Comment by andrewxhill** [comment]
good to close this now right @undercase ?

**Comment by undercase** [comment]
Yep.
