### ISSUE TITLE
Dev app refresh skips // doesn't receive nodeStart event

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1095]
Investigating https://github.com/textileio/photos/issues/1085

Running Dev in Xcode I see the following behavior

1. If you launch via an XCode build everything seems to work well. Additionally, the black loading screen after the logo is very quick.
2. If you _refresh_ via app shake, you get longer black loading screen after the logo. Additionally, the nodeStart event is never captures (or fired). I do see the nodeOnline event start later. This leads to a state like, https://github.com/textileio/photos/issues/1083 where none of my groups or anything are available. (however I still see my avatar, so maybe slightly different).

**Comment by asutula** [comment]
You mention shaking the device, so I assume you're running on a real device?

**Comment by andrewxhill** [comment]
seems to be fixed with the move to sagas. 

the behavior that happens now:

if the app launches in the same way, after being dumped from memory, it will load to the last screen that was open but the ui will be unresponsive for some time.
