### ISSUE TITLE
Contact screen mockup

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1109]
If we're feeling unclear about how to incorporate the list of cafes into this screen, it may be a good time to play with some ideas using mock ups.

**Comment by asutula** [comment]
Feel like we could use some work on mock ups for the contact screen. It's starting to look a but Frankenstein to me.

**Comment by undercase** [comment]
Agreed. I’ll work on a mock-up today.

**Comment by undercase** [comment]
![Contact Screen](https://user-images.githubusercontent.com/2547706/59278112-69546180-8c2f-11e9-98fc-3b729b0f2759.png)

##  Notes

- Top bar stays the same as it is now.
- Buttons have rounded edges.
- Font will be Biotif (mockup is in Roboto).
- I decided to put the `Shared Groups` and `Cafes` lists into a [Tab View](https://github.com/react-native-community/react-native-tab-view). This should solve our spacing issues, is intuitive for users, and will make it easy to add additional sections as the complexity of the application grows. Plus, the library looks great and is fully types with TypeScript.

**Comment by undercase** [comment]
Also could be good to totally avoid box shadows and just use separators, like on the Groups screen. If that sounds better, I can upload a mockup with that design as well.

**Comment by undercase** [comment]
It should be easy to add a simple green/grey dot next to the contact name to reflect whether they're online throughout the UI, re: the conversation @sanderpick and I had about "online" status.
