### ISSUE TITLE
Display cafe url, not peer id

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1125]
For the work around showing Contact cafes and own cafes, let's display the cafe url instead of the peer id. Peer id doesn't mean much since it's so long.

**Comment by sanderpick** [comment]
With the 0.3.0 release (queuing stuff), I've switched back to p2p cafe
connections in the hope that it'll be more reliable now. So, maybe we can
keep this like it is until we've determined whether or not that's going to
work.

**Comment by undercase** [comment]
Okay, I'll leave this as it is for the time being. Changing it from URL -> peer ID is dead simple so I can change this at the drop of a hat.

**Comment by undercase** [comment]
Seems like we've decided peer id is the way to go-good to close this issue now?

**Comment by andrewxhill** [comment]
lots of changes here, closing this specific thing for now. we can open a new one for updates to the current 'bot' look.
