### ISSUE TITLE
Need to sort out "send message" UX on the receiving end

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1129]
Currently, there is no UX at all. If you send a message to a contact, they will never know it happened, they will never see the message. 

The UX we'd want could be what you'd expect... The user is notified of the message and can chose to start participating or decline. What would that take using the tools in our Textile toolbox? Is this just as simple as: In addition to creating the thread, we need to send an invite as well?

**Comment by undercase** [comment]
I think it should be as simple as sending an invite. Should that invite look different from an invitation to join a group?

**Comment by asutula** [comment]
I think the actual invite would probably be the same. @sanderpick can chime in here.

But from a UI/UX perspective maybe we need to move away from using the thread name as the one and only thing that's ever displayed in the UI. This is because what is displayed should be a function of who is viewing the app. So it might be better to have the app derive a "display name" for a thread based on the context of the particular use case the app is providing. In the case of a closed thread with a whitelist of users, the derived display name would be a string of the other users in the thread.

**Comment by asutula** [comment]
I think the actual `Thread.name` is probably just useful for the use case of a group thread where you want to allow participants to set the group name or subject.

**Comment by undercase** [comment]
In #1132 I extend the saga that creates a new group with the ability to send out invites immediately when the group is created. That makes is trivial to fix this issue and send out an invite when the "direct message" button is clicked. I'm going to wait until that PR is merged and then push the fix to this issue.
