### ISSUE TITLE
Contact shared groups list always empty

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1130]
**Describe the bug**
Even when I have a group that a contact has joined, when I view that contact's screen, it says "not a part of any shared groups"

**To Reproduce**
1. Create a group
2. Invite a contact to it
3. Have the contact join the group
4. Go to that contact's screen and see

**Expected behavior**
The shared group should be listed

**Screenshots**

**Smartphone (please complete the following information):**
iOS and Android

**Additional context**
In case it was some sort of data loading timing problem, I tried kill the app and restarting it... Same result.

**Comment by andrewxhill** [comment]
this is fixed from what i see now. close?

**Comment by andrewxhill** [comment]
fixed
