### ISSUE TITLE
can't scroll node logs in android

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1136]
open node logs in android, try to scroll, it wont

it looks as though they are covered by another layer or something, all the text is lighter than on ios. saw this on someone else's phone or i would have grabbed a ss

**Comment by sanderpick** [comment]
I see it too

**Comment by andrewxhill** [comment]
okay, the scroll part sounded familiar, i hit the same in Notes https://github.com/facebook/react-native/issues/15274. not sure about the cloudy overlay
