### ISSUE TITLE
Taken to "Unknown" thread after joining

### ISSUE THREAD

**Issue by sanderpick** [textileio/photos#1141]
After accepting an invite, I'm taken to the attached screen:

![IMG_1522](https://user-images.githubusercontent.com/361000/59124268-1c614a00-8914-11e9-8aad-03ce0831d041.PNG)

**Comment by undercase** [comment]
Does this always happen or just occasionally?

**Comment by andrewxhill** [comment]
another question, where are you taken there from? do you go back to the Groups screen first and then go to an unknown? the flow that _should_ be happening, is that you are taken to Groups screen where you'll see some feedback about the joining state, 

https://github.com/textileio/photos/pull/1047

The Unknown was coming from trying to join a thread before we had the metadata to do so, that PR above introduced the waiting stages.

**Comment by sanderpick** [comment]
I think just occasionally. I'll pay more attention to what happens after hitting the back button if I see it again!
