### ISSUE TITLE
Add cafe registration to on-boarding

### ISSUE THREAD

**Issue by undercase** [textileio/photos#1164]
Select 1+ from list, input other by peer ID.

**Comment by undercase** [comment]
![Cafe Registration Screen](https://user-images.githubusercontent.com/2547706/59540839-eb14eb00-8ecc-11e9-97d2-f2cc15565d96.png)

- The icon at the top is a placeholder. I think a vector graphic of a coffeeshop/cafe would work well here, in line with the graphics displayed on the rest of the onboarding.
- The list of cafes is a scrollview that supports an unlimited amount of cafes.
- The user just chooses one to start with, and can add more from settings.
- Clicking on the search button brings the user to a separate page where they can search and select a cafe by peer ID.
- It might be smart to add a "Learn More" button at the end of the descriptive paragraph, colored in light blue to indicate it's a link, that opens up a link to the [textile docs page on cafes.](https://docs.textile.io/concepts/cafes/)

**Comment by sanderpick** [comment]
Looking good!
- We can tweak the tagline later, but something more like "cafes are trust-less, always-on nodes that assist the peer network"
- We should show the peer ID instead of the static DNS names
- There's no ability to search for a cafe at the moment
- There should be an option to enter your own peer ID
- You should be able to skip the screen (not register)

**Comment by undercase** [comment]
Something like this would probably be better:

![Cafe Registration Screen](https://user-images.githubusercontent.com/2547706/59541973-bd7e7080-8ed1-11e9-8158-349a669ea456.png)

I replaced "Search For a Cafe by Peer ID" with "Enter Your Own Peer ID"-that button was intended to serve that function. The user can opt not to select any cafes to proceed without registering-this will open up a confirmation modal. In the production screen, I will show the peer IDs.

**Comment by sanderpick** [comment]
Sweet 🎉
