### ISSUE TITLE
There is a condition in Group view that can lead to an all white screen

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1169]
I believe this is a RN crash. Here is the description,

```
I closed my phone and re started it.  I get the textile page with my
avatar on the upper left side and the picture with Family in the
center and the circles with the group picture/avatars on the right.
When I click on the family group my phone 'starts' to show a photo and
then immediately goes to a white page and then I can't go anywhere
from there.  I noticed that when I am on the page with the family
group on it I can scroll left to the page with my avatar on it and the
three choice of groups, notifications etc and scroll back to the other
page.  Should I close down textile and reload that?
```

![Screenshot_20190616-132845](https://user-images.githubusercontent.com/370259/59567521-b9626800-9023-11e9-87cf-9a57fb37e166.png)

It would be ideal if we could implement a better way to ensure these always result in hard crashes. Unless maybe this is something different.

**Comment by undercase** [comment]
I encountered this issue occasionally-it has to do with my new code for the ActionSheet throwing a runtime error. My pull request #1166 fixes it.
