### ISSUE TITLE
Choose a Cafe screen needs to wait for online

### ISSUE THREAD

**Issue by asutula** [textileio/photos#1179]
**Describe the bug**
If you try to add a cafe before the node in online, you get a `failed to find any peer in table` error. This screen should block until the node is online.

**Comment by undercase** [comment]
Working on this today; I will disable the UI and have the screen include a "Waiting for node to come online..." message until its ready.

**Comment by asutula** [comment]
Oops, I forgot to close the issue. This is already done.
