### ISSUE TITLE
Cafe list in settings doesn't auto-update on Android

### ISSUE THREAD

**Issue by sanderpick** [textileio/photos#1186]
I'm playing with de-registering and registering... often times the list does not update after a change. Seems to be fine on iOS.

**Comment by undercase** [comment]
The list does update (the sessions are refreshed), but depending on your connection it could take a bit to resolve them. I don't want to manually add/remove cafes from the sessions list, which should always be tied to the API info, if that makes sense.

**Comment by sanderpick** [comment]
Ok, cool. The lib's list of cafe sessions would return very fast though. Happy to close for now.. if I see it again I can provide some steps to reproduce.
