### ISSUE TITLE
Add Custom Cafe

### ISSUE THREAD

**Issue by doodlemania2** [textileio/photos#1187]
**Is your feature request related to a problem? Please describe.**
Ability to specify my own custom cafe that I'm running in photos.

**Describe the solution you'd like**
When I hit +, allow me to select from list of pre populated, or register a custom one.

**Comment by asutula** [comment]
This actually exists now as of yesterday's 0.6.0 release. When you're on the cafes screen (either during onboarding or in settings) there is a magnifying glass icon (misleading, I know... we'll change it) which allows you to enter your own cafe peer id and token.

Also, we'd recommend only having one cafe registered at a time, so you should deregister any previous cafe when adding a new one. Plan is to use IPFS cluster to replicate data among a group of cafes, keeping network traffic from the app to cafes to a minimum.

**Comment by doodlemania2** [comment]
well that's outstanding! thank you @asutula
