### ISSUE TITLE
Crash on photo comment (android)

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1213]
![AndroidScreen](https://user-images.githubusercontent.com/370259/61479312-6d6b5180-a948-11e9-86b9-f59d63df2d66.png)

Only thing the RN log says is

`invalid wire type 4 at offset 360`

**Comment by andrewxhill** [comment]
the issue here, is that when this crash happens, it seems to make the joining of the thread fail even though it will appear as though i've joined successfully (so no other peers will know i'm htere, i'll never get further updates, etc)

**Comment by andrewxhill** [comment]
cc @asutula let me know if you can think of other info i could grab that would be helpful

**Comment by sanderpick** [comment]
FYI, been digging in here this morning.

**Comment by sanderpick** [comment]
I haven't been able to reproduce this one... perhaps is was the result of a particular dev setup? Has anyone else seen this?

**Comment by andrewxhill** [comment]
Android only. I got it in production, and was able to replicate in development. Also, saw it happen to another person while joining the dweb camp group, but not consistent.

**Comment by andrewxhill** [comment]
Just tried again and didn't get the crash...

**Comment by sanderpick** [comment]
I tried Android. I'll keep an eye out.

**Comment by andrewxhill** [comment]
sent about 50 invites around between two instances today and never got this. so thinking it's closable for now

**Comment by andrewxhill** [comment]
Okay, I now get this error in production and on dev anytime I enter a comment into the comment view of a photo.

1. Go to a group
2. Click comment icon under a photo(i've  been doing it against one shared from the same phone)
3. Enter a comment and submit
4. Crash

**Comment by andrewxhill** [comment]
Okay, got more info from reactotron,

![Screen Shot 2019-08-20 at 9 57 57 AM](https://user-images.githubusercontent.com/370259/63367639-2ac6db80-c331-11e9-92e9-26361fdc1f17.png)

if I look at `toFeedItemData` line 23 I see the final line here, `value: model_1.Like.decode(buffer_1.Buffer.from(data, 'base64'))`

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const buffer_1 = require("buffer");
const model_1 = require("./model");
function toFeedItemData(type, block, data) {
    switch (type) {
        case model_1.FeedItemType.Text:
            return {
                type,
                block,
                value: model_1.Text.decode(buffer_1.Buffer.from(data, 'base64'))
            };
        case model_1.FeedItemType.Comment:
            return {
                type,
                block,
                value: model_1.Comment.decode(buffer_1.Buffer.from(data, 'base64'))
            };
        case model_1.FeedItemType.Like:
            return {
                type,
                block,
                value: model_1.Like.decode(buffer_1.Buffer.from(data, 'base64'))
            };
```

Tossed a log on that file and I get,

type: 2 
block: c0445ae7-a771-544f-9bb1-a3b99d51c57b:122186:13
data:

```
Ci5RbWZNZGRNWlo0YVJTaXQ4RHRVOHlYQUdvcHI0U2FYbUQzVExlZVlGclo1RGZDEgsI3M7w6gUQ
mtXObxpzCjBQN01iYXA2NFd5NzY3NWFtV0JWQ3VOVEJOSGpYQ0hHNWtTdDVNUGlZUWh3UDJ6YnIS
D2Rldi1hbmRyZXd4aGlsbBouUW1jWFFta2Q2MW55OFBMZjZQb1Q1UXFQNHFwZ0F6M2dOU2pINE5M
VTY0YkdLSiIGR2ZzaGpjKswNCi5RbWNzYWFVNGdGZ1RKWURFVXRBOWVXZDVzcWZXM1FZbjdweFRI
cUxtWk1BZWFCEjQxMkQzS29vV0ZONGhNM0ViNW5qeG9Xc3VZTkY2N3RIYzF3YUE0MXdjeUFNUXlt
eUhCZTFSGuMMCgYvRmlsZXMS2AwKLlFtY3NhYVU0Z0ZnVEpZREVVdEE5ZVdkNXNxZlczUVluN3B4
VEhxTG1aTUFlYUIaCwjMxvDqBRDM7eEpInMKMFA3TWJhcDY0V3k3Njc1YW1XQlZDdU5UQk5IalhD
SEc1a1N0NU1QaVlRaHdQMnpichIPZGV2LWFuZHJld3hoaWxsGi5RbWNYUW1rZDYxbnk4UExmNlBv
VDVRcVA0cXBnQXozZ05Takg0TkxVNjRiR0tKMocKGroDCgVsYXJnZRKwAwoNL2ltYWdlL3Jlc2l6
ZRIsRzVUMlNYZlpqd25CeWRKdlNESmdaUHNZejViMUJiaVhSdXBBY3ppeVJhUWIaLDdlY1RVM04z
OXM0eXREOXJtOVo1RDl1THFDOXVXQ2JoMnJpQ0o5UTQyZHZqIiwyMXVCQXVTZVFVZHc1YUR1NUNZ
UHhFZmVpTFZldXZrdTFUMjZuV3RKQzg0QyouUW1Rd2NiTEhaR29zR1hCWEZadXRxN3BOaDZtckRX
UkpBSDVnV1kyeHNrYlZ1ZDI8YzRqM0JxNmR3VkhlS3FBRVlYN0VWMnZVY0ZKVWEyN3U2YWRvbXBr
UllZZVlzNEF4U0pYOEgzYXdmeXJFOgppbWFnZS9qcGVnQi5pbWFnZS0wNWQzYjI3Ni1iYmI3LTRk
YjMtYjE3Yy1kYWQ3OTIwZjM1N2QuanBnSJzUBlIMCOrJuOoFEKvO8fABWikKEwoGaGVpZ2h0EgkR
AAAAAACskEAKEgoFd2lkdGgSCREAAAAAAACJQGIuUW1jN1JqUDdaa2tEcG1BaEd3Y3ltd29XVDJB
ZEpoeXJWeENuNkpVaFQyMWdjaRq7AwoFc21hbGwSsQMKDS9pbWFnZS9yZXNpemUSLDhmZ3I5Mjla
TWNCTDliRHk0ajdBRTFycW00RkRjcWJQR1FrcEhGU1JMVVo2Giw3ZWNUVTNOMzlzNHl0RDlybTla
NUQ5dUxxQzl1V0NiaDJyaUNKOVE0MmR2aiIsQ2Fzc0RjcWYxOTJNbmNld2VKS0dKdmhaZnJWOWtC
M0dKUmJ2TlBXbTZyYWEqLlFtTnJmZWlyU1ZiQzhBTXpISmVCYUV1TWRKMUdYcVVUbnJWdmE5Q2dh
ZENvS1IyPTJESGRGQ3kzTlVaZk1qWGc5YXczNXRKWG9IUmg2YTE1VmRkUUEyR29kdHpuR3NlRkY1
TW9iNzhHOXI3Yno6CmltYWdlL2pwZWdCLmltYWdlLTA1ZDNiMjc2LWJiYjctNGRiMy1iMTdjLWRh
ZDc5MjBmMzU3ZC5qcGdIv68BUgwI5cm46gUQt67y4QFaKQoTCgZoZWlnaHQSCREAAAAAALB6QAoS
CgV3aWR0aBIJEQAAAAAAAHRAYi5RbWM3UmpQN1pra0RwbUFoR3djeW13b1dUMkFkSmh5clZ4Q242
SlVoVDIxZ2NpGokDCgV0aHVtYhL/AgoNL2ltYWdlL3Jlc2l6ZRIsM25kZ2pRYmJMU3dXZ0pqSDhy
bmV0ajk0dEVISkJaN0RlUW56U1dybjRkcXIaLEc1VDJTWGZaanduQnlkSnZTREpnWlBzWXo1YjFC
YmlYUnVwQWN6aXlSYVFiIiw3YUdWSjduR2dtSGRxdjhvaUVLWjJaYnJOQnYxelZQM0FEU3VUMnNX
M013VCouUW1ieXl0UktMbkVOZnAzRE52aTNZdWViaHNBRVJaU1RZOG9RZTZFUU1rV2k0aTI8WDY2
RXdhdVhMZHBSRHFMZFFDV0xWcFBydTNqZXFlcXc1WUxNUTJtemFiYnlKNUp1VFBhb1JhVEVQbmtr
OgppbWFnZS9qcGVnSIMeUgwI6sm46gUQy5qT2QJaKQoTCgZoZWlnaHQSCREAAAAAAKBgQAoSCgV3
aWR0aBIJEQAAAAAAAFlAYi5RbWM3UmpQN1pra0RwbUFoR3djeW13b1dUMkFkSmh5clZ4Q242SlVo
VDIxZ2NpSjQxMkQzS29vV0ZONGhNM0ViNW5qeG9Xc3VZTkY2N3RIYzF3YUE0MXdjeUFNUXlteUhC
ZTFSSjQxMkQzS29vV0M1WUY5QVVhY1o5NDd1VDN6UkFCUXlUaGNZZXd6RTE1QVF6WHkxQ3ZYdFpV
Ui5RbWM3UmpQN1pra0RwbUFoR3djeW13b1dUMkFkSmh5clZ4Q242SlVoVDIxZ2Np
```

**Comment by sanderpick** [comment]
My hunch is that this is happening whenever you load your feed, which just happens to be whenever you make a comment. Can you export your repo again? That way we could list the feed with the CLI.

**Comment by andrewxhill** [comment]
still haven't found a good way to do that with android...

**Comment by andrewxhill** [comment]
for fun, i wanted to see what was coming back,

```
            try {
              const value = model_1.Text.decode(buffer_1.Buffer.from(data, 'base64'))
              console.log(value)
            }catch(err){
              console.log('err', 0)
            }

            try {
              const value = model_1.Comment.decode(buffer_1.Buffer.from(data, 'base64'))
              console.log(value)
            }catch(err){
              console.log('err', 1)
            }
            try {
              const value = model_1.Files.decode(buffer_1.Buffer.from(data, 'base64'))
              console.log(value)
            }catch(err){
              console.log('err', 3)
            }

            try {
              const value = model_1.Ignore.decode(buffer_1.Buffer.from(data, 'base64'))
              console.log(value)
            }catch(err){
              console.log('err', 4)
            }
```

The result is my comment,

```
Comment {id: "QmXR481ux9RH61n91T7ySQmC9ZQ3yPkmZEcAf3DaoGWMs5", date: Timestamp, user: User, body: "Gjbdt", target: FeedItem}
body: "Gjbdt"
date: Timestamp {seconds: 1566323379, nanos: 833540629}
id: "QmXR481ux9RH61n91T7ySQmC9ZQ3yPkmZEcAf3DaoGWMs5"
target: FeedItem {block: "QmcsaaU4gFgTJYDEUtA9eWd5sqfW3QYn7pxTHqLmZMAeaB", thread: "12D3KooWFN4hM3Eb5njxoWsuYNF67tHc1waA41wcyAMQymyHBe1R", payload: Any}
user: User {address: "P7Mbap64Wy7675amWBVCuNTBNHjXCHG5kSt5MPiYQhwP2zbr", name: "dev-andrewxhill", avatar: "QmcXQmkd61ny8PLf6PoT5QqP4qpgAz3gNSjH4NLU64bGKJ"}
__proto__: Object
```

so it looks like 

New comment in => some node work => new comment out but marked as type 'like'

**Comment by andrewxhill** [comment]
errors for 0, 3, and 4 (didn't try 2 because that's the known error, like). but success in type 1, comment, even though marked as type 2

**Comment by sanderpick** [comment]
Hmm, ok. Still will need to reproduce this to make a change. Are you seeing this in Beta?

**Comment by sanderpick** [comment]
Actually, it would be great to see in dev, then you can just download the repo from the file explorer.

**Comment by sanderpick** [comment]
Working my way out of the onion here:
- Adding a comment from the CLI and receiving the thread update event in the daemon works
- Doing the same in android-textile tests works (see image below)

![Screenshot 2019-08-20 22 31 37](https://user-images.githubusercontent.com/361000/63405173-b9bc0e00-c39a-11e9-8851-b2437bb8a8ac.png)

**Comment by sanderpick** [comment]
I can't find any crossed wires in the RN SDK. Since the only way to repro so far is with the app, I'll have to spend some time debugging in Android Studio.

**Comment by andrewxhill** [comment]
here's the fun thing. i can get my android install to crash by commenting on a shared photo from my ios install.

**Comment by andrewxhill** [comment]
okay... I think I finally got it,

### RN comment is type=1

https://github.com/textileio/react-native-sdk/blob/master/src/model.ts#L82

###  Android comment is type=2
https://github.com/textileio/android-textile/blob/master/textile/src/main/java/io/textile/textile/FeedItemType.java#L6

###  iOS comment is type=1

https://github.com/textileio/ios-textile/blob/master/Textile/Classes/Model/FeedItemData.h#L23

**Comment by andrewxhill** [comment]
fixed by https://github.com/textileio/android-textile/pull/57
