### ISSUE TITLE
Can't access to local photos

### ISSUE THREAD

**Issue by racuna** [textileio/photos#1216]
**Describe the bug**
Textile app can't access to photos stored in the phone. Even with storage permission enabled.

I can add directly from the camera tho.

**To Reproduce**
1. Sign up
2. Receive the code
3. Open the app
4. Can't access to pics stored, nor add from a gallery app either.

**Expected behavior**
Show pics on the phone like a gallery app. I'm new to the app, so, maybe it's not the case. But the "add photo" does not work either. Only from camera.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 5 pro
 - OS: MIUI 10 (Android 9)

Context:

I was looking for a Google Photo alternative

**Comment by andrewxhill** [comment]
this sounds a lot like this issue i fixed yesterday, https://github.com/textileio/photos/pull/1286

could you try the release pending distribution? it should be available for update 1-2hrs max.
