### ISSUE TITLE
Active buttons are shaded as if inactive in photo feed

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1230]
Via feedback at dweb camp

![button-disabled](https://user-images.githubusercontent.com/370259/61824043-e7507e80-ae11-11e9-80c9-2285c429d2f5.png)

**Comment by undercase** [comment]
The `SEND` button is shaded as inactive because you cannot send an empty message. As soon as you type something, it turns blue to indicate that it is enabled.

**Comment by andrewxhill** [comment]
moving this one over to you Thomas, it's small and you'll be in that code already

**Comment by asutula** [comment]
it's just the button to share a photo that appears inactive. The "Send" button becomes actice once you type something.

**Comment by andrewxhill** [comment]
fixed for a while
