### ISSUE TITLE
App launch from background takes a full UI refresh

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1239]
A few months back I had put a bunch of time into trying to clean up areas of the UI that were taking a full refresh when the app loads from the background. Things like group avatars for example, that should be just visible the second the user loads the app.

That all appears to be lost now. What I see instead is,

1. When you open the app you get a spinner.
2. When the spinner is finished, the UI has a full stream of incremental loading (groups load, groups reorder, avatars load, etc)

#1 makes sense, but definitely not both. Ideally we can get rid of #2 again. Why is that state not being cached anymore so that it is visible once the spinner is complete?

**Comment by asutula** [comment]
The spinner screen is only displayed when the app is loading the UI from scratch. 

This would definitely happen from a cold launch. 

I'm not sure what the behavior is in the case of (on iOS) app suspended -> foreground. We will need to read up on that, but it's possible that iOS chooses to load the UI from scratch in that case. 

The last case app in background -> foreground doesn't display the spinner and the previously existing UI is displayed as expected.

So it's that middle case that we need to research and understand.

**Comment by asutula** [comment]
To clarify, the spinner screen isn't something that is displayed "on top of" the other UI. It is displayed before (in place of) the other UI while the node is being initialized and/or started during a cold launch.

**Comment by andrewxhill** [comment]
just checked, it isn't about the suspension of the app, it's linked to the node shutting down. it will happen every time the node stops and has to restart.

**Comment by asutula** [comment]
I tested that as well and didn't see that behavior. Background the app, let the node stop after 3 min, bring the app into the foreground. All the UI is there and the node just starts and comes online. We have no control over when the app is suspended, so what makes you think the app isn't getting suspended right after the node is stopped? It's possible that when I'm testing it, it's not getting suspended, but when you tested it, it is getting suspended.
