### ISSUE TITLE
Group creation dialog is broken; not clearing name from previous creation

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1240]
1. Go to the Groups screen and click "+"
2. Name a new group and create it.
3. Navigate back to the Groups screen and click "+" again

You'll see that the form already contains the name from your first Group creation. Additionally, if you change that name to something new (or keep it the same) the form wont go anywhere (i.e. no new group can be created).

**Comment by undercase** [comment]
I’ll fix this today.

**Comment by andrewxhill** [comment]
close it?
