### ISSUE TITLE
Node stopped notification fires 2-3 times

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1243]
Pretty consistently when I background the app I get the final "Node stopped" notification 2-3 times back-to-back

**Comment by asutula** [comment]
are you seeing this while running in the sim?

**Comment by asutula** [comment]
i'm suspicious there are some bugs around reloading the RN js in the sim and event listeners not properly getting reset

**Comment by andrewxhill** [comment]
only on device so far, sim looks like single events

**Comment by asutula** [comment]
oh sorry, i guess i meant are you running in dev mode or running prod/beta?

**Comment by andrewxhill** [comment]
production + dev in dev mode

**Comment by andrewxhill** [comment]
haven't seen this guy since the notification cleanup. will reopen if seen again
