### ISSUE TITLE
"Send Message" sends to wrong peer

### ISSUE THREAD

**Issue by sanderpick** [textileio/photos#1245]
Following this UI route:
1. Select contact
2. Tap "send message"

I observed three times in row (just to be sure) an invite being sent to the wrong peer:

```
22:16:50.896 DEBUG   tex-core: delivered message QmVmCCwPP4TY4dpZnt3hH88Sh5bCQLBcwep5Jv8rirQPzV cafe_api_v1.go:252
[GIN] 2019/07/26 - 22:16:50 | 200 |  2.949417185s |     47.33.22.46 | POST     /api/v1/inbox/12D3KooWHhsedg6onw8zbTKaXUghytUGV64PRz2VebjdWABmpkBf/12D3KooWPDEWDyuyiNrrrrUDmM3GahLLx8wWHnm7JTZmLYMq5jDy
```

`12D3KooWPDEWDyuyiNrrrrUDmM3GahLLx8wWHnm7JTZmLYMq5jDy` is indeed a valid peer on the cafe, but not the one I sent the message to.

However, following the similar UI route:

1. Contact
2. Tap "New group" in the upper right corner
3. Select the contact I want

...works fine (the message is sent to the correct peer).

This is of course slightly maddening when debugging unless you can see the logs and are aware of all the mechanisms.

**Comment by undercase** [comment]
This is really confusing me right now, I'm not replicating the problem. Does the whitelist of the new thread that is created also contain the wrong peer?

**Comment by andrewxhill** [comment]
@undercase I'm bumping this up to Critical and this milestone as it appears broken in production afai can tell

**Comment by andrewxhill** [comment]
feel free to just investigate and attach findings here, we can help you solve it. 

you could start with just answering your own question, which peers are in the whitelist and do they match expected

**Comment by undercase** [comment]
Definitely, will solve this today!

**Comment by undercase** [comment]
Okay, finally figured out what was happening here:

- Right now, when you click `SEND MESSAGE`, it successfully creates the thread with the correct contact on the whitelist. Once the thread is created, it calls `Textile.invites.add`. That call is failing with the error `thread is not shareable` and not inviting anyone.
- Why is this happening? I changed the sharing type of p2p threads to be `NOT_SHARED`, which means nobody can invite anyone to the thread. I assumed that you could still send invites to members on the whitelist, but that is not the case.
- The solution is to keep the p2p threads `OPEN` and only use the whitelist to handle access control.
- The SDK call to `Textile.invites.add` is failing with `thread is not shareable` for me, and no invites are being sent. I'm not sure why it is still sending invites for you, but I'm assuming that is a side effect of the code that will go away once the thread sharing is fixed-at least, it started working perfectly for me once I did that.

I apologize for this issue, I should have caught it a long time ago. I honestly totally misunderstood the way thread access control functions. Opening a PR to fix this now.

**Comment by sanderpick** [comment]
Nice @undercase - you could also use INVITE_ONLY for the sharing setting, OPEN for the type. This is understandably confusing... it will be better with the move to role-based access.

**Comment by undercase** [comment]
Thanks @sanderpick. If there is a whitelist and the type is `OPEN`, it seems like whether the sharing setting is `SHARED` or `INVITE_ONLY` doesn't really matter, because in either case the only people the thread can be shared with are the initiator and the other person on the whitelist. I think it makes sense to keep it `SHARED` just because that way if the initiator leaves, the other contact (only person on the whitelist) can still invite them back that way.

**Comment by sanderpick** [comment]
SGTM
