### ISSUE TITLE
Empty notifications screen should revert to art

### ISSUE THREAD

**Issue by sanderpick** [textileio/photos#1246]
On a fresh install, the notifications screen is empty and displays the nice textile art. However, after receiving and deleting a notification (from accepting an invite), the screen just goes all white. In the case, it should revert to showing the nice textile art.

![Screenshot_20190726-151853](https://user-images.githubusercontent.com/361000/61984602-ec503200-afb9-11e9-8a33-0fd415630e57.png)

**Comment by undercase** [comment]
From what I can see, this is because the `FeedList` is set to only display the art during the "tour," which is disabled when the user receives their first notification. I'm going to just detach it from the tour logic and display the art whenever there are no notifications to show.

**Comment by andrewxhill** [comment]
dunno if the state still works like it used to, but that used to lead to this ugly condition where sometimes it takes awhile to load notifications and while it is doing that it shows the tour screen for a second. Just look out for that.

**Comment by undercase** [comment]
Ah, I'll see if I can have it display nothing while the notifications request (not sure if that's how it's handled, will look??) is pending.

**Comment by undercase** [comment]
There is a way to display nothing while the notifications are refreshing, but using that would mean when the user refreshed notifications and the art was already being displayed, the art would disappear during the refresh, which probably isn't what we want.

**Comment by andrewxhill** [comment]
closable?
