### ISSUE TITLE
Messages against existing photo post to bottom of "feed"

### ISSUE THREAD

**Issue by doodlemania2** [textileio/photos#1254]
**Describe the bug**
Messages being entered to a photo are not being attached to the photo, they are going in as plain messages in a new 'thread?'

**To Reproduce**
1. Post some photos
2. Scroll up to one
3. Try to enter a comment on a photo
4. Comment goes to the bottom, not onto the photo

**Expected behavior**
Photo message should stay together.

**Comment by andrewxhill** [comment]
Duplicate of https://github.com/textileio/photos/issues/1226

This should be fixed in the release out today

**Comment by doodlemania2** [comment]
sorry about that!
