### ISSUE TITLE
Custom Cafe Invitations

### ISSUE THREAD

**Issue by doodlemania2** [textileio/photos#1256]
**Is your feature request related to a problem? Please describe.**
It is hard to get the information about a custom cafe to end users. Currently, I have to send two text messages to friends and family members and explain the string starting with X is the peer and the string starting with Y is the token.

**Describe the solution you'd like**
Provide an 'invitation' to a cafe capability (this may have to go into go-textile) but essentially is an invite to a thread that contains instructions to the app to add my cafe to it. Prompt the user: "You've been invited to a custom cafe, do you accept?" If yes, add the cafe. If no, take no action.

**Describe alternatives you've considered**
This could also be done with a text message handler, similar to inviting to a "group"

**Comment by andrewxhill** [comment]
interesting... seems totally doable. i'll take a stab at this one soon

**Comment by andrewxhill** [comment]
https://github.com/textileio/photos/pull/1319

should be in the release next week
