### ISSUE TITLE
RFC: app redux caching of available groups

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#1265]
The issue reported here https://github.com/textileio/photos/issues/1239 is the result of thread metadata not being cached in redux (i.e. not part of any of the redux whitelists).

### Discussion

We could just add it to a whitelist, but 2 primary issues with that.

1. The thread metadata is part of the PhotoViewing redux, which contains a lot of stuff we don't really need cached in redux: https://github.com/textileio/photos/blob/master/App/Redux/PhotoViewingRedux.ts
2. The threads themselves are stored as metadata with nested photo data. Ideally we don't need to be caching photo data. There may be cases where we want a photo or a page of photos cached, but definitely not the entire thread.

### Proposal

* Break the 'threads' component out of the PhotoViewing redux. 
* Break the threads metadata and files into two different entries, perhaps structuring them as two parts of a new reducer (similar to what was done with a group https://github.com/textileio/photos/tree/master/App/features/group). 

By doing the above we could whitelist the thread metadata simply. Additionally, it could simplify the paging of thread file feeds by un-nesting them from the thread metadata.

**Comment by asutula** [comment]
Yea that sounds like a good plan. I saw the same things when I recently dug into the redux state code to unify all the photo processing code. Turns out the `IFiles` data stored in in `PhotoViewingRedux` isn't even used anymore (we now use feed data in the `features/group/feed` redux. I was close to just cleaning that up already, but things are a bit tangled in that area of the app and I needed to think it through a bit. You plan sounds good and I think it needs to be done anyway just to clean up that part of the redux state and remove unused data and queries for that data.

**Comment by andrewxhill** [comment]
okay so 

* Break the threads metadata and files into two different entries, perhaps structuring them as two parts of a new reducer (similar to what was done with a group https://github.com/textileio/photos/tree/master/App/features/group).

would actually become just

* Remove the file list from the threads metadata as it's already stored elsewhere in redux

**Comment by asutula** [comment]
Yea

**Comment by asutula** [comment]
Another issue is that the groups screen you're trying to optimize depends on contact data as well. That would also need to be persisted.

**Comment by andrewxhill** [comment]
right, we could explore storing groups metadata in this redux entry. e.g. the threads metadata as it is now, then for each thread we'd also have,

* latest photo thumb data
* the top N (currently 8) most recently active contacts
* then finally having the contact feed cached too

will need to feel that out as i look closer, but that would be enough to have that whole view be totally static on launch time. simple to update continuously after just as it is done now

**Comment by asutula** [comment]
I don't doubt this path is worth going down, but just for context and background, I don't think we ever persisted this group data in the past. I've been looking at the git history and can't see it.

**Comment by asutula** [comment]
Another more potential goal related to this:

If startup time is a UX thing we want to optimize, we can look at removing as much blocking UI from the app as possible (we currently block the UI completely while the node is being started, for example), and instead, look at displaying cached/persisted data as soon as possible and then presenting blocking UI only where necessary. 

For example, the app launches and we immediately display the persisted list of groups. You tap on a group and immediately start typing a message. The node isn't yet started, so the 'send' button is disabled until the node is started.

It's a more surgical approach that allows better UX, but is also more work.

**Comment by asutula** [comment]
re: this data never previously being persisted... The persistence configuration as been in `RootRedcer.ts` for the last couple of months, but was in a file `App/Config/ReduxPersist.ts` previously.

**Comment by andrewxhill** [comment]
Okay, can't tell you what happened there... but i just did some fiddling to see how to make the redux pretty stable for first load. here's my proposal for the initial task.

Okay, for reference, here's the state I'm focusing in on, https://github.com/textileio/photos/blob/master/App/Redux/PhotoViewingRedux.ts#L122

1. Rename photoViewingRedux to something else, maybe groupsRedux since it has little to do with photoViewing.
2. Move the photoViewing specific things into a real photoViewing redux if possible. Those include just the last 4-5 elements in the state object shared above.
3. Remove `photos` from the `ThreadData` which is the type of the `threads` parameter in the state. Here's the threadData, https://github.com/textileio/photos/blob/master/App/Redux/PhotoViewingRedux.ts#L98
4. If I remove that, there are a couple of downstream filter/get methods that relied on it that I'll need to clean up. I saw things like, getting all threads shared with a comment (right now its a pretty complicated map/filter method that maybe we need to push down to a sqllite query enabled by the node). but I'll need to investigate.
5. there are a couple new and helpful pieces of metadata that i can add quickly to the threadData object (updated date, thumbnail) that will make everything else run just really smooth to start.
6. add the new redux, whatever it's called, groupRedux or whatever, to the cached state to reload quickly when the app comes back into memory. I did a quick test of this just by refreshing the sim with this data available and it gets us my target outcome => The app will launch and load the spinner, immediately after the spinner finishes, there is already groups UI to view. I can make the ordering of those groups very stable too so it doesnt' jump around a lot.

All this should help later additions to possibly get rid of the spinner or whatever, but it feels like the first right step.

**Comment by andrewxhill** [comment]
More info, that array of photos in every thread in threadData is duplicated every time you load the feed entry in the group redux, so needless memory consumption.

**Comment by andrewxhill** [comment]
it looks like contacts would be 'nice to have' but adding them to the groups ui is decoupled, so we could look into that as a secondary project

**Comment by andrewxhill** [comment]
i can break down the above work a bit more even

1. reconfigure the state and actions to work without the embedded photos list + add that new state to the persist whitelist
2. then we can look at breaking that redux apart into 2 or more

**Comment by andrewxhill** [comment]
kept poking at this today, looks like a clean path. i think i can pr it on sunday
