### ISSUE TITLE
Create UI for a user rename a Thread

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#706]

**Comment by undercase** [comment]
This is finished; the code is in the `thomas/renameThread` branch. Right now, it appears that the API for renaming threads causes an error, so I'm going to hold off on creating a pull request until that issue is resolved.

**Comment by undercase** [comment]
Some thoughts: Right now, pressing “Rename Group” opens a modal for renaming, and once the user submits the new name, it closes the modal. The saga takes it from there - after successfully calling `Textile.threads.rename`, it puts the `refreshThreadRequest` action, which will update the thread’s name in the state and thus update the thread being viewed. Although there may be a small lag between when the user submits the new name and when the new name is actually shown in the UI, I think it’s fine. To get rid of the lag, I could add another action to `PhotoViewingRedux` that manually updates the name in the state as soon as the user submits the new name, and then `refreshThreadRequest` will bring the state back in line with the API after `Textile.threads.rename` is called in the saga. Not sure if that’s best practice.

**Comment by asutula** [comment]
Sounds like good progress. Get that PR open in draft mode and let's discuss it there. 

First thought that comes to mind: The modal should stay up until the name is actually updated. Also provides a place to display an error if there was one, plus eliminates the issue about the old name being shown for a split second after the modal is dismissed.

**Comment by undercase** [comment]
Fixed in #1097.
