### ISSUE TITLE
App needs a retry button for initial cafe dial attemp failure

### ISSUE THREAD

**Issue by andrewxhill** [textileio/photos#890]
Currently if the first dial attempts fail the app will error our in an unusable state

![screenshot_20190201-094450](https://user-images.githubusercontent.com/370259/52140128-d8c59f00-2606-11e9-9584-a31601ec9b77.png)

I'm not sure how/where to catch that error, and if we do, can I give some sensible information (e.g. "Be sure to check your internet connection which is required to connect to the Textile & IPFS network") and a "Retry" button.

**Comment by andrewxhill** [comment]
is this still a possible issue @asutula @sanderpick ?

**Comment by sanderpick** [comment]
with the cafes part of onboarding, i could see a retry button after selecting one

**Comment by andrewxhill** [comment]
now via url, fixed
