### ISSUE TITLE
Incorrect number of 'likes' on a single Photo

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/photos#958]
**Describe the bug**
A user noticed that some of the pictures in a group have more likes on them than there are people in the group.

**To Reproduce**
1. Create a group
2. Share invite link and have peers join
3. Create post, have member 'like' the post
4. Check post 'likes', count is greater than number of participants

**Expected behavior**
This should only ever be, at most, equal to the number of participants in the group

**Comment by asutula** [comment]
Yea, with the new UI code, I may have opened back up the possibility to tap quickly while the first like is processing async, and add multiple likes.

**Comment by carsonfarmer** [comment]
Ah ok, I wondered about that... Good to know.
